package io.github.katarem.mtgrestclient.scryfallmodels

import com.google.gson.annotations.SerializedName


data class ScryFallInfo (

    @SerializedName("object"            ) var objectType          : String?           = null,
    @SerializedName("id"                ) var id              : String?           = null,
    @SerializedName("oracle_id"         ) var oracleId        : String?           = null,
    @SerializedName("multiverse_ids"    ) var multiverseIds   : ArrayList<Int>    = arrayListOf(),
    @SerializedName("mtgo_id"           ) var mtgoId          : Int?              = null,
    @SerializedName("tcgplayer_id"      ) var tcgplayerId     : Int?              = null,
    @SerializedName("cardmarket_id"     ) var cardmarketId    : Int?              = null,
    @SerializedName("name"              ) var name            : String?           = null,
    @SerializedName("lang"              ) var lang            : String?           = null,
    @SerializedName("released_at"       ) var releasedAt      : String?           = null,
    @SerializedName("uri"               ) var uri             : String?           = null,
    @SerializedName("scryfall_uri"      ) var scryfallUri     : String?           = null,
    @SerializedName("layout"            ) var layout          : String?           = null,
    @SerializedName("highres_image"     ) var highresImage    : Boolean?          = null,
    @SerializedName("image_status"      ) var imageStatus     : String?           = null,
    @SerializedName("image_uris"        ) var imageUris       : ImageUris?        = ImageUris(),
    @SerializedName("mana_cost"         ) var manaCost        : String?           = null,
    @SerializedName("cmc"               ) var cmc             : Int?              = null,
    @SerializedName("type_line"         ) var typeLine        : String?           = null,
    @SerializedName("oracle_text"       ) var oracleText      : String?           = null,
    @SerializedName("power"             ) var power           : String?           = null,
    @SerializedName("toughness"         ) var toughness       : String?           = null,
    @SerializedName("colors"            ) var colors          : ArrayList<String> = arrayListOf(),
    @SerializedName("color_identity"    ) var colorIdentity   : ArrayList<String> = arrayListOf(),
    @SerializedName("keywords"          ) var keywords        : ArrayList<String> = arrayListOf(),
    @SerializedName("legalities"        ) var legalities      : Legalities?       = Legalities(),
    @SerializedName("games"             ) var games           : ArrayList<String> = arrayListOf(),
    @SerializedName("reserved"          ) var reserved        : Boolean?          = null,
    @SerializedName("foil"              ) var foil            : Boolean?          = null,
    @SerializedName("nonfoil"           ) var nonfoil         : Boolean?          = null,
    @SerializedName("finishes"          ) var finishes        : ArrayList<String> = arrayListOf(),
    @SerializedName("oversized"         ) var oversized       : Boolean?          = null,
    @SerializedName("promo"             ) var promo           : Boolean?          = null,
    @SerializedName("reprint"           ) var reprint         : Boolean?          = null,
    @SerializedName("variation"         ) var variation       : Boolean?          = null,
    @SerializedName("set_id"            ) var setId           : String?           = null,
    @SerializedName("set"               ) var set             : String?           = null,
    @SerializedName("set_name"          ) var setName         : String?           = null,
    @SerializedName("set_type"          ) var setType         : String?           = null,
    @SerializedName("set_uri"           ) var setUri          : String?           = null,
    @SerializedName("set_search_uri"    ) var setSearchUri    : String?           = null,
    @SerializedName("scryfall_set_uri"  ) var scryfallSetUri  : String?           = null,
    @SerializedName("rulings_uri"       ) var rulingsUri      : String?           = null,
    @SerializedName("prints_search_uri" ) var printsSearchUri : String?           = null,
    @SerializedName("collector_number"  ) var collectorNumber : String?           = null,
    @SerializedName("digital"           ) var digital         : Boolean?          = null,
    @SerializedName("rarity"            ) var rarity          : String?           = null,
    @SerializedName("card_back_id"      ) var cardBackId      : String?           = null,
    @SerializedName("artist"            ) var artist          : String?           = null,
    @SerializedName("artist_ids"        ) var artistIds       : ArrayList<String> = arrayListOf(),
    @SerializedName("illustration_id"   ) var illustrationId  : String?           = null,
    @SerializedName("border_color"      ) var borderColor     : String?           = null,
    @SerializedName("frame"             ) var frame           : String?           = null,
    @SerializedName("frame_effects"     ) var frameEffects    : ArrayList<String> = arrayListOf(),
    @SerializedName("security_stamp"    ) var securityStamp   : String?           = null,
    @SerializedName("full_art"          ) var fullArt         : Boolean?          = null,
    @SerializedName("textless"          ) var textless        : Boolean?          = null,
    @SerializedName("booster"           ) var booster         : Boolean?          = null,
    @SerializedName("story_spotlight"   ) var storySpotlight  : Boolean?          = null,
    @SerializedName("edhrec_rank"       ) var edhrecRank      : Int?              = null,
    @SerializedName("preview"           ) var preview         : Preview?          = Preview(),
    @SerializedName("prices"            ) var prices          : Prices?           = Prices(),
    @SerializedName("related_uris"      ) var relatedUris     : RelatedUris?      = RelatedUris(),
    @SerializedName("purchase_uris"     ) var purchaseUris    : PurchaseUris?     = PurchaseUris()

)